// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

package messages;

public final class CompanyProto {
  private CompanyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code stocks.Company}
   */
  public enum Company
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GOOGLE = 0;</code>
     */
    GOOGLE(0),
    /**
     * <code>APPLE = 1;</code>
     */
    APPLE(1),
    /**
     * <code>MICROSOFT = 2;</code>
     */
    MICROSOFT(2),
    /**
     * <code>IBM = 3;</code>
     */
    IBM(3),
    /**
     * <code>ORACLE = 4;</code>
     */
    ORACLE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GOOGLE = 0;</code>
     */
    public static final int GOOGLE_VALUE = 0;
    /**
     * <code>APPLE = 1;</code>
     */
    public static final int APPLE_VALUE = 1;
    /**
     * <code>MICROSOFT = 2;</code>
     */
    public static final int MICROSOFT_VALUE = 2;
    /**
     * <code>IBM = 3;</code>
     */
    public static final int IBM_VALUE = 3;
    /**
     * <code>ORACLE = 4;</code>
     */
    public static final int ORACLE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Company valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Company forNumber(int value) {
      switch (value) {
        case 0: return GOOGLE;
        case 1: return APPLE;
        case 2: return MICROSOFT;
        case 3: return IBM;
        case 4: return ORACLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Company>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Company> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Company>() {
            public Company findValueByNumber(int number) {
              return Company.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return messages.CompanyProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Company[] VALUES = values();

    public static Company valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Company(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:stocks.Company)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcompany.proto\022\006stocks*D\n\007Company\022\n\n\006GO" +
      "OGLE\020\000\022\t\n\005APPLE\020\001\022\r\n\tMICROSOFT\020\002\022\007\n\003IBM\020" +
      "\003\022\n\n\006ORACLE\020\004B\030\n\010messagesB\014CompanyProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
