// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscription.proto

package messages;

public final class SubscriptionProto {
  private SubscriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:stocks.Subscription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string subscriber_id = 1;</code>
     * @return The subscriberId.
     */
    java.lang.String getSubscriberId();
    /**
     * <code>string subscriber_id = 1;</code>
     * @return The bytes for subscriberId.
     */
    com.google.protobuf.ByteString
        getSubscriberIdBytes();

    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    java.util.List<messages.SubscriptionProto.Subscription.Filter> 
        getFiltersList();
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    messages.SubscriptionProto.Subscription.Filter getFilters(int index);
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    int getFiltersCount();
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    java.util.List<? extends messages.SubscriptionProto.Subscription.FilterOrBuilder> 
        getFiltersOrBuilderList();
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    messages.SubscriptionProto.Subscription.FilterOrBuilder getFiltersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code stocks.Subscription}
   */
  public static final class Subscription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:stocks.Subscription)
      SubscriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscription() {
      subscriberId_ = "";
      filters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Subscription();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Subscription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              subscriberId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                filters_ = new java.util.ArrayList<messages.SubscriptionProto.Subscription.Filter>();
                mutable_bitField0_ |= 0x00000001;
              }
              filters_.add(
                  input.readMessage(messages.SubscriptionProto.Subscription.Filter.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          filters_ = java.util.Collections.unmodifiableList(filters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.SubscriptionProto.internal_static_stocks_Subscription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.SubscriptionProto.internal_static_stocks_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.SubscriptionProto.Subscription.class, messages.SubscriptionProto.Subscription.Builder.class);
    }

    public interface FilterOrBuilder extends
        // @@protoc_insertion_point(interface_extends:stocks.Subscription.Filter)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string field_name = 1;</code>
       * @return The fieldName.
       */
      java.lang.String getFieldName();
      /**
       * <code>string field_name = 1;</code>
       * @return The bytes for fieldName.
       */
      com.google.protobuf.ByteString
          getFieldNameBytes();

      /**
       * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
       * @return The enum numeric value on the wire for operator.
       */
      int getOperatorValue();
      /**
       * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
       * @return The operator.
       */
      messages.SubscriptionProto.Subscription.Filter.Operator getOperator();

      /**
       * <code>.stocks.Company company = 3;</code>
       * @return The enum numeric value on the wire for company.
       */
      int getCompanyValue();
      /**
       * <code>.stocks.Company company = 3;</code>
       * @return The company.
       */
      messages.CompanyProto.Company getCompany();

      /**
       * <code>double stock_value = 4;</code>
       * @return The stockValue.
       */
      double getStockValue();

      /**
       * <code>double change = 5;</code>
       * @return The change.
       */
      double getChange();

      /**
       * <code>double variation = 6;</code>
       * @return The variation.
       */
      double getVariation();

      /**
       * <code>int64 date = 7;</code>
       * @return The date.
       */
      long getDate();

      public messages.SubscriptionProto.Subscription.Filter.ValueCase getValueCase();
    }
    /**
     * Protobuf type {@code stocks.Subscription.Filter}
     */
    public static final class Filter extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:stocks.Subscription.Filter)
        FilterOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Filter.newBuilder() to construct.
      private Filter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Filter() {
        fieldName_ = "";
        operator_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Filter();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Filter(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                fieldName_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                operator_ = rawValue;
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                valueCase_ = 3;
                value_ = rawValue;
                break;
              }
              case 33: {
                valueCase_ = 4;
                value_ = input.readDouble();
                break;
              }
              case 41: {
                valueCase_ = 5;
                value_ = input.readDouble();
                break;
              }
              case 49: {
                valueCase_ = 6;
                value_ = input.readDouble();
                break;
              }
              case 56: {
                valueCase_ = 7;
                value_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.SubscriptionProto.internal_static_stocks_Subscription_Filter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.SubscriptionProto.internal_static_stocks_Subscription_Filter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.SubscriptionProto.Subscription.Filter.class, messages.SubscriptionProto.Subscription.Filter.Builder.class);
      }

      /**
       * Protobuf enum {@code stocks.Subscription.Filter.Operator}
       */
      public enum Operator
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>GT = 0;</code>
         */
        GT(0),
        /**
         * <code>GTEQ = 1;</code>
         */
        GTEQ(1),
        /**
         * <code>L = 2;</code>
         */
        L(2),
        /**
         * <code>LEQ = 3;</code>
         */
        LEQ(3),
        /**
         * <code>EQ = 4;</code>
         */
        EQ(4),
        /**
         * <code>NEQ = 5;</code>
         */
        NEQ(5),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>GT = 0;</code>
         */
        public static final int GT_VALUE = 0;
        /**
         * <code>GTEQ = 1;</code>
         */
        public static final int GTEQ_VALUE = 1;
        /**
         * <code>L = 2;</code>
         */
        public static final int L_VALUE = 2;
        /**
         * <code>LEQ = 3;</code>
         */
        public static final int LEQ_VALUE = 3;
        /**
         * <code>EQ = 4;</code>
         */
        public static final int EQ_VALUE = 4;
        /**
         * <code>NEQ = 5;</code>
         */
        public static final int NEQ_VALUE = 5;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static Operator valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static Operator forNumber(int value) {
          switch (value) {
            case 0: return GT;
            case 1: return GTEQ;
            case 2: return L;
            case 3: return LEQ;
            case 4: return EQ;
            case 5: return NEQ;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Operator>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            Operator> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Operator>() {
                public Operator findValueByNumber(int number) {
                  return Operator.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return messages.SubscriptionProto.Subscription.Filter.getDescriptor().getEnumTypes().get(0);
        }

        private static final Operator[] VALUES = values();

        public static Operator valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private Operator(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:stocks.Subscription.Filter.Operator)
      }

      private int valueCase_ = 0;
      private java.lang.Object value_;
      public enum ValueCase
          implements com.google.protobuf.Internal.EnumLite,
              com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        COMPANY(3),
        STOCK_VALUE(4),
        CHANGE(5),
        VARIATION(6),
        DATE(7),
        VALUE_NOT_SET(0);
        private final int value;
        private ValueCase(int value) {
          this.value = value;
        }
        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ValueCase valueOf(int value) {
          return forNumber(value);
        }

        public static ValueCase forNumber(int value) {
          switch (value) {
            case 3: return COMPANY;
            case 4: return STOCK_VALUE;
            case 5: return CHANGE;
            case 6: return VARIATION;
            case 7: return DATE;
            case 0: return VALUE_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public ValueCase
      getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public static final int FIELD_NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object fieldName_;
      /**
       * <code>string field_name = 1;</code>
       * @return The fieldName.
       */
      @java.lang.Override
      public java.lang.String getFieldName() {
        java.lang.Object ref = fieldName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldName_ = s;
          return s;
        }
      }
      /**
       * <code>string field_name = 1;</code>
       * @return The bytes for fieldName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFieldNameBytes() {
        java.lang.Object ref = fieldName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OPERATOR_FIELD_NUMBER = 2;
      private int operator_;
      /**
       * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
       * @return The enum numeric value on the wire for operator.
       */
      @java.lang.Override public int getOperatorValue() {
        return operator_;
      }
      /**
       * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
       * @return The operator.
       */
      @java.lang.Override public messages.SubscriptionProto.Subscription.Filter.Operator getOperator() {
        @SuppressWarnings("deprecation")
        messages.SubscriptionProto.Subscription.Filter.Operator result = messages.SubscriptionProto.Subscription.Filter.Operator.valueOf(operator_);
        return result == null ? messages.SubscriptionProto.Subscription.Filter.Operator.UNRECOGNIZED : result;
      }

      public static final int COMPANY_FIELD_NUMBER = 3;
      /**
       * <code>.stocks.Company company = 3;</code>
       * @return The enum numeric value on the wire for company.
       */
      public int getCompanyValue() {
        if (valueCase_ == 3) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>.stocks.Company company = 3;</code>
       * @return The company.
       */
      public messages.CompanyProto.Company getCompany() {
        if (valueCase_ == 3) {
          @SuppressWarnings("deprecation")
          messages.CompanyProto.Company result = messages.CompanyProto.Company.valueOf(
              (java.lang.Integer) value_);
          return result == null ? messages.CompanyProto.Company.UNRECOGNIZED : result;
        }
        return messages.CompanyProto.Company.GOOGLE;
      }

      public static final int STOCK_VALUE_FIELD_NUMBER = 4;
      /**
       * <code>double stock_value = 4;</code>
       * @return The stockValue.
       */
      @java.lang.Override
      public double getStockValue() {
        if (valueCase_ == 4) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }

      public static final int CHANGE_FIELD_NUMBER = 5;
      /**
       * <code>double change = 5;</code>
       * @return The change.
       */
      @java.lang.Override
      public double getChange() {
        if (valueCase_ == 5) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }

      public static final int VARIATION_FIELD_NUMBER = 6;
      /**
       * <code>double variation = 6;</code>
       * @return The variation.
       */
      @java.lang.Override
      public double getVariation() {
        if (valueCase_ == 6) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }

      public static final int DATE_FIELD_NUMBER = 7;
      /**
       * <code>int64 date = 7;</code>
       * @return The date.
       */
      @java.lang.Override
      public long getDate() {
        if (valueCase_ == 7) {
          return (java.lang.Long) value_;
        }
        return 0L;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getFieldNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldName_);
        }
        if (operator_ != messages.SubscriptionProto.Subscription.Filter.Operator.GT.getNumber()) {
          output.writeEnum(2, operator_);
        }
        if (valueCase_ == 3) {
          output.writeEnum(3, ((java.lang.Integer) value_));
        }
        if (valueCase_ == 4) {
          output.writeDouble(
              4, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 5) {
          output.writeDouble(
              5, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 6) {
          output.writeDouble(
              6, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 7) {
          output.writeInt64(
              7, (long)((java.lang.Long) value_));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getFieldNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldName_);
        }
        if (operator_ != messages.SubscriptionProto.Subscription.Filter.Operator.GT.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, operator_);
        }
        if (valueCase_ == 3) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, ((java.lang.Integer) value_));
        }
        if (valueCase_ == 4) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(
                4, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 5) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(
                5, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 6) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(
                6, (double)((java.lang.Double) value_));
        }
        if (valueCase_ == 7) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(
                7, (long)((java.lang.Long) value_));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof messages.SubscriptionProto.Subscription.Filter)) {
          return super.equals(obj);
        }
        messages.SubscriptionProto.Subscription.Filter other = (messages.SubscriptionProto.Subscription.Filter) obj;

        if (!getFieldName()
            .equals(other.getFieldName())) return false;
        if (operator_ != other.operator_) return false;
        if (!getValueCase().equals(other.getValueCase())) return false;
        switch (valueCase_) {
          case 3:
            if (getCompanyValue()
                != other.getCompanyValue()) return false;
            break;
          case 4:
            if (java.lang.Double.doubleToLongBits(getStockValue())
                != java.lang.Double.doubleToLongBits(
                    other.getStockValue())) return false;
            break;
          case 5:
            if (java.lang.Double.doubleToLongBits(getChange())
                != java.lang.Double.doubleToLongBits(
                    other.getChange())) return false;
            break;
          case 6:
            if (java.lang.Double.doubleToLongBits(getVariation())
                != java.lang.Double.doubleToLongBits(
                    other.getVariation())) return false;
            break;
          case 7:
            if (getDate()
                != other.getDate()) return false;
            break;
          case 0:
          default:
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FIELD_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFieldName().hashCode();
        hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + operator_;
        switch (valueCase_) {
          case 3:
            hash = (37 * hash) + COMPANY_FIELD_NUMBER;
            hash = (53 * hash) + getCompanyValue();
            break;
          case 4:
            hash = (37 * hash) + STOCK_VALUE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getStockValue()));
            break;
          case 5:
            hash = (37 * hash) + CHANGE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getChange()));
            break;
          case 6:
            hash = (37 * hash) + VARIATION_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getVariation()));
            break;
          case 7:
            hash = (37 * hash) + DATE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getDate());
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static messages.SubscriptionProto.Subscription.Filter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(messages.SubscriptionProto.Subscription.Filter prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code stocks.Subscription.Filter}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:stocks.Subscription.Filter)
          messages.SubscriptionProto.Subscription.FilterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return messages.SubscriptionProto.internal_static_stocks_Subscription_Filter_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return messages.SubscriptionProto.internal_static_stocks_Subscription_Filter_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  messages.SubscriptionProto.Subscription.Filter.class, messages.SubscriptionProto.Subscription.Filter.Builder.class);
        }

        // Construct using messages.SubscriptionProto.Subscription.Filter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          fieldName_ = "";

          operator_ = 0;

          valueCase_ = 0;
          value_ = null;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return messages.SubscriptionProto.internal_static_stocks_Subscription_Filter_descriptor;
        }

        @java.lang.Override
        public messages.SubscriptionProto.Subscription.Filter getDefaultInstanceForType() {
          return messages.SubscriptionProto.Subscription.Filter.getDefaultInstance();
        }

        @java.lang.Override
        public messages.SubscriptionProto.Subscription.Filter build() {
          messages.SubscriptionProto.Subscription.Filter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public messages.SubscriptionProto.Subscription.Filter buildPartial() {
          messages.SubscriptionProto.Subscription.Filter result = new messages.SubscriptionProto.Subscription.Filter(this);
          result.fieldName_ = fieldName_;
          result.operator_ = operator_;
          if (valueCase_ == 3) {
            result.value_ = value_;
          }
          if (valueCase_ == 4) {
            result.value_ = value_;
          }
          if (valueCase_ == 5) {
            result.value_ = value_;
          }
          if (valueCase_ == 6) {
            result.value_ = value_;
          }
          if (valueCase_ == 7) {
            result.value_ = value_;
          }
          result.valueCase_ = valueCase_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof messages.SubscriptionProto.Subscription.Filter) {
            return mergeFrom((messages.SubscriptionProto.Subscription.Filter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(messages.SubscriptionProto.Subscription.Filter other) {
          if (other == messages.SubscriptionProto.Subscription.Filter.getDefaultInstance()) return this;
          if (!other.getFieldName().isEmpty()) {
            fieldName_ = other.fieldName_;
            onChanged();
          }
          if (other.operator_ != 0) {
            setOperatorValue(other.getOperatorValue());
          }
          switch (other.getValueCase()) {
            case COMPANY: {
              setCompanyValue(other.getCompanyValue());
              break;
            }
            case STOCK_VALUE: {
              setStockValue(other.getStockValue());
              break;
            }
            case CHANGE: {
              setChange(other.getChange());
              break;
            }
            case VARIATION: {
              setVariation(other.getVariation());
              break;
            }
            case DATE: {
              setDate(other.getDate());
              break;
            }
            case VALUE_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          messages.SubscriptionProto.Subscription.Filter parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (messages.SubscriptionProto.Subscription.Filter) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int valueCase_ = 0;
        private java.lang.Object value_;
        public ValueCase
            getValueCase() {
          return ValueCase.forNumber(
              valueCase_);
        }

        public Builder clearValue() {
          valueCase_ = 0;
          value_ = null;
          onChanged();
          return this;
        }


        private java.lang.Object fieldName_ = "";
        /**
         * <code>string field_name = 1;</code>
         * @return The fieldName.
         */
        public java.lang.String getFieldName() {
          java.lang.Object ref = fieldName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            fieldName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string field_name = 1;</code>
         * @return The bytes for fieldName.
         */
        public com.google.protobuf.ByteString
            getFieldNameBytes() {
          java.lang.Object ref = fieldName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fieldName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string field_name = 1;</code>
         * @param value The fieldName to set.
         * @return This builder for chaining.
         */
        public Builder setFieldName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          fieldName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string field_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFieldName() {
          
          fieldName_ = getDefaultInstance().getFieldName();
          onChanged();
          return this;
        }
        /**
         * <code>string field_name = 1;</code>
         * @param value The bytes for fieldName to set.
         * @return This builder for chaining.
         */
        public Builder setFieldNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          fieldName_ = value;
          onChanged();
          return this;
        }

        private int operator_ = 0;
        /**
         * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
         * @return The enum numeric value on the wire for operator.
         */
        @java.lang.Override public int getOperatorValue() {
          return operator_;
        }
        /**
         * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
         * @param value The enum numeric value on the wire for operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperatorValue(int value) {
          
          operator_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
         * @return The operator.
         */
        @java.lang.Override
        public messages.SubscriptionProto.Subscription.Filter.Operator getOperator() {
          @SuppressWarnings("deprecation")
          messages.SubscriptionProto.Subscription.Filter.Operator result = messages.SubscriptionProto.Subscription.Filter.Operator.valueOf(operator_);
          return result == null ? messages.SubscriptionProto.Subscription.Filter.Operator.UNRECOGNIZED : result;
        }
        /**
         * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
         * @param value The operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperator(messages.SubscriptionProto.Subscription.Filter.Operator value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          operator_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.stocks.Subscription.Filter.Operator operator = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearOperator() {
          
          operator_ = 0;
          onChanged();
          return this;
        }

        /**
         * <code>.stocks.Company company = 3;</code>
         * @return The enum numeric value on the wire for company.
         */
        @java.lang.Override
        public int getCompanyValue() {
          if (valueCase_ == 3) {
            return ((java.lang.Integer) value_).intValue();
          }
          return 0;
        }
        /**
         * <code>.stocks.Company company = 3;</code>
         * @param value The enum numeric value on the wire for company to set.
         * @return This builder for chaining.
         */
        public Builder setCompanyValue(int value) {
          valueCase_ = 3;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.stocks.Company company = 3;</code>
         * @return The company.
         */
        @java.lang.Override
        public messages.CompanyProto.Company getCompany() {
          if (valueCase_ == 3) {
            @SuppressWarnings("deprecation")
            messages.CompanyProto.Company result = messages.CompanyProto.Company.valueOf(
                (java.lang.Integer) value_);
            return result == null ? messages.CompanyProto.Company.UNRECOGNIZED : result;
          }
          return messages.CompanyProto.Company.GOOGLE;
        }
        /**
         * <code>.stocks.Company company = 3;</code>
         * @param value The company to set.
         * @return This builder for chaining.
         */
        public Builder setCompany(messages.CompanyProto.Company value) {
          if (value == null) {
            throw new NullPointerException();
          }
          valueCase_ = 3;
          value_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.stocks.Company company = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCompany() {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>double stock_value = 4;</code>
         * @return The stockValue.
         */
        public double getStockValue() {
          if (valueCase_ == 4) {
            return (java.lang.Double) value_;
          }
          return 0D;
        }
        /**
         * <code>double stock_value = 4;</code>
         * @param value The stockValue to set.
         * @return This builder for chaining.
         */
        public Builder setStockValue(double value) {
          valueCase_ = 4;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double stock_value = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearStockValue() {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>double change = 5;</code>
         * @return The change.
         */
        public double getChange() {
          if (valueCase_ == 5) {
            return (java.lang.Double) value_;
          }
          return 0D;
        }
        /**
         * <code>double change = 5;</code>
         * @param value The change to set.
         * @return This builder for chaining.
         */
        public Builder setChange(double value) {
          valueCase_ = 5;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double change = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearChange() {
          if (valueCase_ == 5) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>double variation = 6;</code>
         * @return The variation.
         */
        public double getVariation() {
          if (valueCase_ == 6) {
            return (java.lang.Double) value_;
          }
          return 0D;
        }
        /**
         * <code>double variation = 6;</code>
         * @param value The variation to set.
         * @return This builder for chaining.
         */
        public Builder setVariation(double value) {
          valueCase_ = 6;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double variation = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearVariation() {
          if (valueCase_ == 6) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <code>int64 date = 7;</code>
         * @return The date.
         */
        public long getDate() {
          if (valueCase_ == 7) {
            return (java.lang.Long) value_;
          }
          return 0L;
        }
        /**
         * <code>int64 date = 7;</code>
         * @param value The date to set.
         * @return This builder for chaining.
         */
        public Builder setDate(long value) {
          valueCase_ = 7;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 date = 7;</code>
         * @return This builder for chaining.
         */
        public Builder clearDate() {
          if (valueCase_ == 7) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:stocks.Subscription.Filter)
      }

      // @@protoc_insertion_point(class_scope:stocks.Subscription.Filter)
      private static final messages.SubscriptionProto.Subscription.Filter DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new messages.SubscriptionProto.Subscription.Filter();
      }

      public static messages.SubscriptionProto.Subscription.Filter getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Filter>
          PARSER = new com.google.protobuf.AbstractParser<Filter>() {
        @java.lang.Override
        public Filter parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Filter(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Filter> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Filter> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public messages.SubscriptionProto.Subscription.Filter getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SUBSCRIBER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object subscriberId_;
    /**
     * <code>string subscriber_id = 1;</code>
     * @return The subscriberId.
     */
    @java.lang.Override
    public java.lang.String getSubscriberId() {
      java.lang.Object ref = subscriberId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscriberId_ = s;
        return s;
      }
    }
    /**
     * <code>string subscriber_id = 1;</code>
     * @return The bytes for subscriberId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubscriberIdBytes() {
      java.lang.Object ref = subscriberId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscriberId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILTERS_FIELD_NUMBER = 2;
    private java.util.List<messages.SubscriptionProto.Subscription.Filter> filters_;
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    @java.lang.Override
    public java.util.List<messages.SubscriptionProto.Subscription.Filter> getFiltersList() {
      return filters_;
    }
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends messages.SubscriptionProto.Subscription.FilterOrBuilder> 
        getFiltersOrBuilderList() {
      return filters_;
    }
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    @java.lang.Override
    public int getFiltersCount() {
      return filters_.size();
    }
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    @java.lang.Override
    public messages.SubscriptionProto.Subscription.Filter getFilters(int index) {
      return filters_.get(index);
    }
    /**
     * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
     */
    @java.lang.Override
    public messages.SubscriptionProto.Subscription.FilterOrBuilder getFiltersOrBuilder(
        int index) {
      return filters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubscriberIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subscriberId_);
      }
      for (int i = 0; i < filters_.size(); i++) {
        output.writeMessage(2, filters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubscriberIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subscriberId_);
      }
      for (int i = 0; i < filters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, filters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof messages.SubscriptionProto.Subscription)) {
        return super.equals(obj);
      }
      messages.SubscriptionProto.Subscription other = (messages.SubscriptionProto.Subscription) obj;

      if (!getSubscriberId()
          .equals(other.getSubscriberId())) return false;
      if (!getFiltersList()
          .equals(other.getFiltersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBSCRIBER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriberId().hashCode();
      if (getFiltersCount() > 0) {
        hash = (37 * hash) + FILTERS_FIELD_NUMBER;
        hash = (53 * hash) + getFiltersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static messages.SubscriptionProto.Subscription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.SubscriptionProto.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static messages.SubscriptionProto.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static messages.SubscriptionProto.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(messages.SubscriptionProto.Subscription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code stocks.Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:stocks.Subscription)
        messages.SubscriptionProto.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return messages.SubscriptionProto.internal_static_stocks_Subscription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return messages.SubscriptionProto.internal_static_stocks_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                messages.SubscriptionProto.Subscription.class, messages.SubscriptionProto.Subscription.Builder.class);
      }

      // Construct using messages.SubscriptionProto.Subscription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFiltersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subscriberId_ = "";

        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return messages.SubscriptionProto.internal_static_stocks_Subscription_descriptor;
      }

      @java.lang.Override
      public messages.SubscriptionProto.Subscription getDefaultInstanceForType() {
        return messages.SubscriptionProto.Subscription.getDefaultInstance();
      }

      @java.lang.Override
      public messages.SubscriptionProto.Subscription build() {
        messages.SubscriptionProto.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public messages.SubscriptionProto.Subscription buildPartial() {
        messages.SubscriptionProto.Subscription result = new messages.SubscriptionProto.Subscription(this);
        int from_bitField0_ = bitField0_;
        result.subscriberId_ = subscriberId_;
        if (filtersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            filters_ = java.util.Collections.unmodifiableList(filters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.filters_ = filters_;
        } else {
          result.filters_ = filtersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof messages.SubscriptionProto.Subscription) {
          return mergeFrom((messages.SubscriptionProto.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(messages.SubscriptionProto.Subscription other) {
        if (other == messages.SubscriptionProto.Subscription.getDefaultInstance()) return this;
        if (!other.getSubscriberId().isEmpty()) {
          subscriberId_ = other.subscriberId_;
          onChanged();
        }
        if (filtersBuilder_ == null) {
          if (!other.filters_.isEmpty()) {
            if (filters_.isEmpty()) {
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFiltersIsMutable();
              filters_.addAll(other.filters_);
            }
            onChanged();
          }
        } else {
          if (!other.filters_.isEmpty()) {
            if (filtersBuilder_.isEmpty()) {
              filtersBuilder_.dispose();
              filtersBuilder_ = null;
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filtersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFiltersFieldBuilder() : null;
            } else {
              filtersBuilder_.addAllMessages(other.filters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        messages.SubscriptionProto.Subscription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (messages.SubscriptionProto.Subscription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object subscriberId_ = "";
      /**
       * <code>string subscriber_id = 1;</code>
       * @return The subscriberId.
       */
      public java.lang.String getSubscriberId() {
        java.lang.Object ref = subscriberId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subscriberId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subscriber_id = 1;</code>
       * @return The bytes for subscriberId.
       */
      public com.google.protobuf.ByteString
          getSubscriberIdBytes() {
        java.lang.Object ref = subscriberId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subscriberId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscriber_id = 1;</code>
       * @param value The subscriberId to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriberId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subscriberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subscriber_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubscriberId() {
        
        subscriberId_ = getDefaultInstance().getSubscriberId();
        onChanged();
        return this;
      }
      /**
       * <code>string subscriber_id = 1;</code>
       * @param value The bytes for subscriberId to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriberIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subscriberId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<messages.SubscriptionProto.Subscription.Filter> filters_ =
        java.util.Collections.emptyList();
      private void ensureFiltersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          filters_ = new java.util.ArrayList<messages.SubscriptionProto.Subscription.Filter>(filters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          messages.SubscriptionProto.Subscription.Filter, messages.SubscriptionProto.Subscription.Filter.Builder, messages.SubscriptionProto.Subscription.FilterOrBuilder> filtersBuilder_;

      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public java.util.List<messages.SubscriptionProto.Subscription.Filter> getFiltersList() {
        if (filtersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filters_);
        } else {
          return filtersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public int getFiltersCount() {
        if (filtersBuilder_ == null) {
          return filters_.size();
        } else {
          return filtersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public messages.SubscriptionProto.Subscription.Filter getFilters(int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);
        } else {
          return filtersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder setFilters(
          int index, messages.SubscriptionProto.Subscription.Filter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.set(index, value);
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder setFilters(
          int index, messages.SubscriptionProto.Subscription.Filter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.set(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder addFilters(messages.SubscriptionProto.Subscription.Filter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder addFilters(
          int index, messages.SubscriptionProto.Subscription.Filter value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(index, value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder addFilters(
          messages.SubscriptionProto.Subscription.Filter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder addFilters(
          int index, messages.SubscriptionProto.Subscription.Filter.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder addAllFilters(
          java.lang.Iterable<? extends messages.SubscriptionProto.Subscription.Filter> values) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, filters_);
          onChanged();
        } else {
          filtersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder clearFilters() {
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public Builder removeFilters(int index) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.remove(index);
          onChanged();
        } else {
          filtersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public messages.SubscriptionProto.Subscription.Filter.Builder getFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public messages.SubscriptionProto.Subscription.FilterOrBuilder getFiltersOrBuilder(
          int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);  } else {
          return filtersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public java.util.List<? extends messages.SubscriptionProto.Subscription.FilterOrBuilder> 
           getFiltersOrBuilderList() {
        if (filtersBuilder_ != null) {
          return filtersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filters_);
        }
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public messages.SubscriptionProto.Subscription.Filter.Builder addFiltersBuilder() {
        return getFiltersFieldBuilder().addBuilder(
            messages.SubscriptionProto.Subscription.Filter.getDefaultInstance());
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public messages.SubscriptionProto.Subscription.Filter.Builder addFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().addBuilder(
            index, messages.SubscriptionProto.Subscription.Filter.getDefaultInstance());
      }
      /**
       * <code>repeated .stocks.Subscription.Filter filters = 2;</code>
       */
      public java.util.List<messages.SubscriptionProto.Subscription.Filter.Builder> 
           getFiltersBuilderList() {
        return getFiltersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          messages.SubscriptionProto.Subscription.Filter, messages.SubscriptionProto.Subscription.Filter.Builder, messages.SubscriptionProto.Subscription.FilterOrBuilder> 
          getFiltersFieldBuilder() {
        if (filtersBuilder_ == null) {
          filtersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              messages.SubscriptionProto.Subscription.Filter, messages.SubscriptionProto.Subscription.Filter.Builder, messages.SubscriptionProto.Subscription.FilterOrBuilder>(
                  filters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          filters_ = null;
        }
        return filtersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:stocks.Subscription)
    }

    // @@protoc_insertion_point(class_scope:stocks.Subscription)
    private static final messages.SubscriptionProto.Subscription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new messages.SubscriptionProto.Subscription();
    }

    public static messages.SubscriptionProto.Subscription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscription>
        PARSER = new com.google.protobuf.AbstractParser<Subscription>() {
      @java.lang.Override
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subscription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Subscription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public messages.SubscriptionProto.Subscription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stocks_Subscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stocks_Subscription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stocks_Subscription_Filter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stocks_Subscription_Filter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022subscription.proto\022\006stocks\032\rcompany.pr" +
      "oto\"\344\002\n\014Subscription\022\025\n\rsubscriber_id\030\001 " +
      "\001(\t\022,\n\007filters\030\002 \003(\0132\033.stocks.Subscripti" +
      "on.Filter\032\216\002\n\006Filter\022\022\n\nfield_name\030\001 \001(\t" +
      "\0226\n\010operator\030\002 \001(\0162$.stocks.Subscription" +
      ".Filter.Operator\022\"\n\007company\030\003 \001(\0162\017.stoc" +
      "ks.CompanyH\000\022\025\n\013stock_value\030\004 \001(\001H\000\022\020\n\006c" +
      "hange\030\005 \001(\001H\000\022\023\n\tvariation\030\006 \001(\001H\000\022\016\n\004da" +
      "te\030\007 \001(\003H\000\"=\n\010Operator\022\006\n\002GT\020\000\022\010\n\004GTEQ\020\001" +
      "\022\005\n\001L\020\002\022\007\n\003LEQ\020\003\022\006\n\002EQ\020\004\022\007\n\003NEQ\020\005B\007\n\005val" +
      "ueB\035\n\010messagesB\021SubscriptionProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          messages.CompanyProto.getDescriptor(),
        });
    internal_static_stocks_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stocks_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stocks_Subscription_descriptor,
        new java.lang.String[] { "SubscriberId", "Filters", });
    internal_static_stocks_Subscription_Filter_descriptor =
      internal_static_stocks_Subscription_descriptor.getNestedTypes().get(0);
    internal_static_stocks_Subscription_Filter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stocks_Subscription_Filter_descriptor,
        new java.lang.String[] { "FieldName", "Operator", "Company", "StockValue", "Change", "Variation", "Date", "Value", });
    messages.CompanyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
